### ISSUE TITLE
Background > Technical definitions: Maybe mention r-universe as a repository

### ISSUE THREAD

**Issue by fkohrt** [lmu-osc/introduction-to-renv#23]
I reckon R users a increasingly likely to come across this: https://r-universe.dev/

**Comment by NeuroShepherd** [comment]
I like the idea of r-universe and including this in principle, but I think something that people will unknowingly run into when using r-universe is that there's no management of package dependencies by r-universe itself. CRAN (and I think BioC) nominally run regression tests when packages are updated so that the dependencies and reverse dependencies of all packages are compatible.

(This isn't strictly true though--CRAN will notify maintainers of reverse dependent packages when breaking changes occur, and will eventually remove packages if they don't receive appropriate updates.)

**Comment by NeuroShepherd** [comment]
Also the packages uploaded to r-universe don't even have to pass R CMD Checks:

> 12.3 Are packages on R-universe required to pass CMD check or meet other criteria?
> No.  R-universe is an open publishing system. The system just builds and deploys R packages from git into personal cran-like repositories. The owner of the universe is responsible for their own policies and quality control.

**Comment by NeuroShepherd** [comment]
Ok I think I've settled on mentioning it as an in-development project that essentially unifies packages on CRAN, BioC, and user-uploaded GitHub packages.

**Comment by fkohrt** [comment]
:+1: Technically, r-universe hosts one repository per user and allows any Git remote, not only GitHub.
